auto_commit: false
auto_sync: true
git_integration: true
hybrid_structure:
  auto_classification: true
  auto_enhancement: true
  custom_numbering: null
  custom_structure: null
  enabled: true
  numbering_system: ten_step
  structure_validation: true
  structure_version: hybrid_v1
project_name: Claude Knowledge Catalyst
project_root: /home/driller/repo/claude-knowledge-catalyst
sync_targets:
- enabled: true
  metadata: {}
  name: knowledge-hub
  path: /home/driller/Documents/Obsidian/Knowledge-Hub
  type: obsidian
- enabled: true
  metadata: {}
  name: test-empty
  path: /tmp/test-empty-vault
  type: obsidian
- enabled: true
  metadata: {}
  name: test-clean
  path: /tmp/test-empty-vault
  type: obsidian
tags:
  category_tags:
  - prompt
  - code
  - concept
  - resource
  - project_log
  - command
  claude_tags:
  - opus
  - sonnet
  - haiku
  quality_tags:
  - high
  - medium
  - low
  - experimental
  status_tags:
  - draft
  - tested
  - production
  - deprecated
  tech_tags:
  - python
  - javascript
  - react
  - nodejs
template_path: /home/driller/repo/claude-knowledge-catalyst/templates
version: '2.0'
watch:
  claude_md_patterns:
  - CLAUDE.md
  - .claude/CLAUDE.md
  claude_md_sections_exclude:
  - '# secrets'
  - '# private'
  - '# confidential'
  debounce_seconds: 1.0
  file_patterns:
  - '*.md'
  - '*.txt'
  ignore_patterns:
  - .git
  - __pycache__
  - '*.pyc'
  - .claude/commands
  include_claude_md: true
  watch_paths:
  - .claude
