name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I am using the latest version of Claude Knowledge Catalyst
          required: true
        - label: I have read the documentation
          required: true

  - type: input
    id: version
    attributes:
      label: CKC Version
      description: What version of Claude Knowledge Catalyst are you using?
      placeholder: "v0.10.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.5"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command `ckc init`
        2. Configure vault with `ckc add my-vault /path/to/vault`
        3. Run `ckc sync`
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Please paste any error messages or stack traces
      render: shell
      placeholder: |
        Paste error output here...

  - type: textarea
    id: config-file
    attributes:
      label: Configuration File
      description: Please share your ckc_config.yaml (remove any sensitive information)
      render: yaml
      placeholder: |
        # Your ckc_config.yaml content (remove sensitive info)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: component
    attributes:
      label: Affected Components
      description: Which components seem to be affected? (Check all that apply)
      options:
        - label: CLI Commands
        - label: Obsidian Integration
        - label: Configuration Management
        - label: File Watching/Syncing
        - label: AI Classification
        - label: Template System
        - label: Documentation